=== budak7273/ContentLib_Documentation/JsonSchemas/CL_VisualKit.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://raw.githubusercontent.com/budak7273/ContentLib_Documentation/main/JsonSchemas/CL_VisualKit.json",
    "title": "ContentLib Visual Kit",
    "description": "ContentLib Visual Kit struct definitions can be made from this JSON, and when converted to JSON, will follow this form.",
    "$comment": "This is NOT a copy-paste template! Check the docs to see how to use this! https://docs.ficsit.app/contentlib/latest/index.html",
    "type": "object",
    "additionalProperties": false,
    "properties": {
        "Mesh": {
            "type": "string",
            "description": "Full asset path to the Mesh for dropped item and belt display. The path must be inside a packaged mod or the base game",
            "examples": [
                "/Game/FactoryGame/Resource/Parts/PackagedWater/SM_PackedWater_01.SM_PackedWater_01"
            ]
        },
        "BigIcon": {
            "type": "string",
            "description": "File name of a PNG in your mod's /ContentLib/Icons folder, OR full asset path to an Icon texture, inside a packaged mod",
            "examples": [
                "/Game/FactoryGame/Resource/RawResources/Water/UI/LiquidWater_Pipe_512.LiquidWater_Pipe_512",
                "MyIconName_512"
            ]
        },
        "SmallIcon": {
            "type": "string",
            "description": "File name of a PNG in your mod's /ContentLib/Icons folder, OR full asset path to an Icon texture inside a packaged mod",
            "examples": [
                "/Game/FactoryGame/Resource/RawResources/Water/UI/LiquidWater_Pipe_256.LiquidWater_Pipe_256",
                "MyIconName_256"
            ]
        },
        "FluidColor": {
            "description": "Controls the color of a Liquid, and the primary color of a Gas",
            "$ref": "Components/CL_RGBA_Color.json"
        },
        "GasColor": {
            "description": "Controls the secondary color of a Gas",
            "$ref": "Components/CL_RGBA_Color.json"
        }
    },
    "patternProperties": {
        "schema": {
            "$comment": "Allow the $schema line in files",
            "type": "string"
        },
        "comment": {
            "$comment": "Allow the $comment line in files",
            "type": "string"
        }
    }
}

=== budak7273/ContentLib_Documentation/JsonSchemas/Tests/Kit_BaseGameWater.json
{
    "$schema": "./../CL_VisualKit.json",
    "Mesh": "/Game/FactoryGame/Resource/Parts/PackagedWater/SM_PackedWater_01.SM_PackedWater_01",
    "BigIcon": "/Game/FactoryGame/Resource/RawResources/Water/UI/LiquidWater_Pipe_512.LiquidWater_Pipe_512",
    "SmallIcon": "/Game/FactoryGame/Resource/RawResources/Water/UI/LiquidWater_Pipe_256.LiquidWater_Pipe_256",
    "FluidColor": {
        "r": 122,
        "g": 176,
        "b": 212,
        "a": 255
    },
    "GasColor": {
        "r": 122,
        "g": 176,
        "b": 212,
        "a": 255
    }
}
